name: Deploy React App to EC2

on:
  push:
    branches:
      - main  # Branche qui déclenche le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/TON_REPO  # adapte le chemin à ton repo cloné sur le serveur
            git pull origin main
            npm install
            npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/
            sudo systemctl restart nginx
          EOF